const actionTypes = {
  SET_RESPONSE_HEADERS: "SET_RESPONSE_HEADERS",
  SET_CURRENT_USER_PROFILE: "SET_CURRENT_USER_PROFILE",
  SET_CURRENT_USER_PLAYLIST: "SET_CURRENT_USER_PLAYLIST",
  SET_NEW_RELEASES: "SET_NEW_RELEASES",
  SET_RECOMMENDATIONS: "SET_RECOMMENDATIONS",
  SET_FEATURED_PLAYLISTS: "SET_FEATURED_PLAYLISTS",
};

export default actionTypes;
